version: "2.1"
orbs:
  coveralls: coveralls/coveralls@2.2.1
  jobs:
    build:
      docker:
        - image: circleci/node:10.0.0
          steps:
            - checkout
        - run:
            command: npm install && make test-coverage
            name: Install and Make
        - coveralls/upload
workflows: null
